In [22]:
import time, sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
# Set random seed for reproducibility
np.random.seed(42)

### 1: ARRAY CREATION & PROPERTIES

#### 1.1 Array Creation Methods

In [24]:
# Using built-in functions
prices_list = [4500.25, 4512.30, 4498.75, 4523.10, 4535.20]
prices_array = np.array(prices_list)

print(f"From list: {prices_array}")
print(f"Data type: {prices_array.dtype}")
print(f"Shape: {prices_array.shape}")

From list: [4500.25 4512.3  4498.75 4523.1  4535.2 ]
Data type: float64
Shape: (5,)


In [25]:
prices_array.reshape(5,1)

array([[4500.25],
       [4512.3 ],
       [4498.75],
       [4523.1 ],
       [4535.2 ]])

In [4]:
# Using built-in functions
zeros_array = np.zeros(5)
ones_array = np.ones(10) 
range_array = np.arange(0, 100, 10)  # Start, stop, step
linspace_array = np.linspace(0, 1, 11)  # Start, stop, number of points

print(f"\nZeros array: {zeros_array}")
print(f"Ones array: {ones_array}")
print(f"Range array: {range_array}")
print(f"Linspace array: {linspace_array}")


Zeros array: [0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Range array: [ 0 10 20 30 40 50 60 70 80 90]
Linspace array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [5]:
# Random arrays for simulations
random_returns = np.random.normal(0.001, 0.02, 252)  # Daily returns simulation
print(f"\nRandom returns sample: {random_returns[:5]}")


Random returns sample: [ 0.01093428 -0.00176529  0.01395377  0.0314606  -0.00368307]


#### 1.2 Data types and memory efficiency

In [6]:
# Different data types
int_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=bool)

print(f"Integer array: {int_array} (dtype: {int_array.dtype})")
print(f"Float array: {float_array} (dtype: {float_array.dtype})")
print(f"Boolean array: {bool_array} (dtype: {bool_array.dtype})")


Integer array: [1 2 3 4 5] (dtype: int32)
Float array: [1.1 2.2 3.3] (dtype: float64)
Boolean array: [ True False  True] (dtype: bool)


In [7]:
# Memory usage comparison
large_int32 = np.ones(1000000, dtype=np.int32)
large_int64 = np.ones(1000000, dtype=np.int64)
print(f"\nMemory usage int32: {large_int32.nbytes / 1024 / 1024:.2f} MB")
print(f"Memory usage int64: {large_int64.nbytes / 1024 / 1024:.2f} MB")


Memory usage int32: 3.81 MB
Memory usage int64: 7.63 MB


#### 1.3 Shape manipulation

In [8]:
# Creating multi-dimensional arrays
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Matrix:\n{matrix_2d}")
print(f"Shape: {matrix_2d.shape}")
print(f"Number of dimensions: {matrix_2d.ndim}")
print(f"Total elements: {matrix_2d.size}")

2D Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Total elements: 9


In [9]:
# Reshaping arrays
portfolio_returns = np.random.normal(0.08, 0.15, 60)  # 5 years of annual returns
monthly_returns = portfolio_returns.reshape(5, 12)  # Reshape to 5 years x 12 months
print(f"\nPortfolio returns reshaped to 5 years x 12 months:")
print(f"Shape: {monthly_returns.shape}")
print(f"First year: {monthly_returns[0]}")


Portfolio returns reshaped to 5 years x 12 months:
Shape: (5, 12)
First year: [ 0.39832343  0.23486979 -0.14790549  0.00736489  0.27003667 -0.02615042
  0.14657291  0.19619511 -0.05903957  0.0710712  -0.4061901  -0.07365815]


In [10]:
# Flattening arrays
flattened = monthly_returns.flatten()
print(f"Flattened back to 1D: {flattened.shape}")

Flattened back to 1D: (60,)


### 2: PYTHON LISTS VS NUMPY ARRAYS

#### 2.1 Memory usage comparison

In [11]:
# Create equivalent data structures
size = 10000
python_list = list(range(size))
numpy_array = np.arange(size)

In [12]:
# Calculate memory usage
list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)
array_memory = numpy_array.nbytes + numpy_array.__sizeof__()

In [13]:
print(f"Data size: {size:,} integers")
print(f"Python list memory: {list_memory:,} bytes ({list_memory/1024/1024:.2f} MB)")
print(f"NumPy array memory: {array_memory:,} bytes ({array_memory/1024/1024:.2f} MB)")
print(f"Memory reduction: {list_memory/array_memory:.1f}x less memory with NumPy")
print(f"Memory savings: {(list_memory - array_memory):,} bytes")

Data size: 10,000 integers
Python list memory: 360,056 bytes (0.34 MB)
NumPy array memory: 160,112 bytes (0.15 MB)
Memory reduction: 2.2x less memory with NumPy
Memory savings: 199,944 bytes


NumPy consumes less resources because it stores data in contiguous memory blocks with fixed, low-overhead data types, unlike Python lists which store pointers to individual Python objects with extra memory overhead. This makes NumPy arrays more compact and faster for numerical operations.

#### 2.2 Basic operations performance comparison

In [14]:
# Test different sizes to show scalability
test_sizes = [1000, 10000, 100000, 500000]

In [15]:
print("Size\t\tList Time\tNumPy Time\tSpeedup")
print("-" * 55)
for size in test_sizes:
    # Create test data
    list_a = list(range(size))
    list_b = list(range(size, 2*size))
    array_a = np.arange(size)
    array_b = np.arange(size, 2*size)
    
    # Time list addition
    start_time = time.time()
    list_result = [a + b for a, b in zip(list_a, list_b)]
    list_time = time.time() - start_time
    
    # Time numpy addition
    start_time = time.time()
    array_result = array_a + array_b
    numpy_time = time.time() - start_time
    
    speedup = list_time / numpy_time if numpy_time > 0 else float('inf')
    print(f"{size:,}\t\t{list_time:.6f}s\t{numpy_time:.6f}s\t{speedup:.1f}x")

Size		List Time	NumPy Time	Speedup
-------------------------------------------------------
1,000		0.000075s	0.000042s	1.8x
10,000		0.000650s	0.001136s	0.6x
100,000		0.005305s	0.000292s	18.2x
500,000		0.024766s	0.001247s	19.9x


#### 2.3 Complex mathematical operations

In [16]:
size = 100000
print(f"\nTesting with {size:,} elements:")

# Create test data
python_list = [float(i) for i in range(size)]
numpy_array = np.arange(size, dtype=float)

print("\n📊 Operation Comparison:")
operations = [
    ("Element-wise multiplication", lambda x: [i * 2.5 for i in x], lambda x: x * 2.5),
    ("Square root", lambda x: [i**0.5 for i in x], lambda x: np.sqrt(x)),
    ("Exponential", lambda x: [2.71828**i for i in x[:100]], lambda x: np.exp(x[:100])),  # Much smaller size for exp
    ("Trigonometric (sin)", lambda x: [np.sin(i) for i in x[:10000]], lambda x: np.sin(x[:10000]))  # Smaller size
]

for op_name, list_op, numpy_op in operations:
    try:
        # Time list operation
        start_time = time.time()
        list_result = list_op(python_list)
        list_time = time.time() - start_time
        
        # Time numpy operation  
        start_time = time.time()
        numpy_result = numpy_op(numpy_array)
        numpy_time = time.time() - start_time
        
        speedup = list_time / numpy_time if numpy_time > 0 else float('inf')
        print(f"  {op_name:25s}: List={list_time:.6f}s, NumPy={numpy_time:.6f}s, Speedup={speedup:.1f}x")
    except OverflowError:
        print(f"  {op_name:25s}: Operation resulted in overflow - values too large to compute")



Testing with 100,000 elements:

📊 Operation Comparison:
  Element-wise multiplication: List=0.011216s, NumPy=0.000211s, Speedup=53.2x
  Square root              : List=0.003836s, NumPy=0.000132s, Speedup=29.0x
  Exponential              : List=0.000384s, NumPy=0.000011s, Speedup=35.0x
  Trigonometric (sin)      : List=0.003592s, NumPy=0.000043s, Speedup=83.7x


#### 2.4 Matrix operations: The real power of NumPy

##### 2.4.1 Matrix creation comparison

In [18]:
matrix_size = 1000

# Python list approach (nested lists)
start_time = time.time()
python_matrix = [[i*j for j in range(matrix_size)] for i in range(matrix_size)]
list_creation_time = time.time() - start_time

# NumPy approach
start_time = time.time()
numpy_matrix = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
numpy_creation_time = time.time() - start_time

print(f"  {matrix_size}x{matrix_size} matrix creation:")
print(f"  Python lists: {list_creation_time:.6f}s")
print(f"  NumPy arrays: {numpy_creation_time:.6f}s")
print(f"  Creation speedup: {list_creation_time/numpy_creation_time:.1f}x faster")

  1000x1000 matrix creation:
  Python lists: 0.026102s
  NumPy arrays: 0.000984s
  Creation speedup: 26.5x faster


##### 2.4.2 Matrix multiplication: The ultimate test

In [19]:
matrix_sizes = [50, 100, 200, 300]
print("Size\t\tPython Lists\tNumPy Arrays\tSpeedup\t\tComplexity")
print("-" * 70)

for size in matrix_sizes:
    # Create matrices
    # Python: nested lists
    matrix_a_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]
    matrix_b_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]
    
    # NumPy: arrays
    matrix_a_np = np.random.rand(size, size)
    matrix_b_np = np.random.rand(size, size)
    
    # Python list matrix multiplication (manual implementation)
    start_time = time.time()
    result_list = [[sum(matrix_a_list[i][k] * matrix_b_list[k][j] for k in range(size)) 
                   for j in range(size)] for i in range(size)]
    list_time = time.time() - start_time
    
    # NumPy matrix multiplication
    start_time = time.time()
    result_np = np.dot(matrix_a_np, matrix_b_np)
    numpy_time = time.time() - start_time
    
    speedup = list_time / numpy_time if numpy_time > 0 else float('inf')
    complexity = f"O(n³) = O({size**3:,})"
    
    print(f"{size}x{size}\t\t{list_time:.6f}s\t{numpy_time:.6f}s\t{speedup:.0f}x\t\t{complexity}")

Size		Python Lists	NumPy Arrays	Speedup		Complexity
----------------------------------------------------------------------
50x50		0.005277s	0.003099s	2x		O(n³) = O(125,000)
100x100		0.039234s	0.000052s	755x		O(n³) = O(1,000,000)
200x200		0.334360s	0.000123s	2718x		O(n³) = O(8,000,000)
300x300		1.345573s	0.001610s	836x		O(n³) = O(27,000,000)


### 2.5 Why NumPy is Faster: Technical Deep Dive

1. **C Implementation**:
   - NumPy core is written in C, not Python
   - Direct memory access without Python overhead
   - Optimized assembly instructions (BLAS/LAPACK)

2. **Vectorization**:
   - Single instruction operates on multiple data (SIMD)
   - CPU can process multiple elements simultaneously
   - Eliminates Python's interpreted loop overhead

3. **Memory Layout**:
   - Contiguous memory allocation
   - Better cache locality and memory access patterns
   - Homogeneous data types (no type checking overhead)

4. **Optimized Algorithms**:
   - Uses highly optimized mathematical libraries
   - Parallel processing capabilities
   - Advanced algorithms for complex operations

5. **Less Python Overhead**:
   - Minimal Python function call overhead
   - Direct memory manipulation
   - Compiled code execution vs interpreted code

### 3. Practical vectorization examples

#### 3.1 Vectorization & Broadcasting in NumPy

#### Vectorization
- Allows operations on entire arrays without explicit loops
- Performs element-wise operations efficiently
- Leverages optimized C code and CPU SIMD instructions

#### Broadcasting
- Allows operations between arrays of different shapes
- Automatically expands smaller arrays to match larger ones
- Rules:
1. Arrays must have same number of dimensions, or
2. One array can have fewer dimensions
3. Size of each dimension must be equal or 1

The following cells demonstrate these concepts with a portfolio analysis example:
- Calculating portfolio values (vectorization)
- Applying price changes across different stocks (broadcasting)


In [43]:
# Example 01
a = np.ones(6)
b = np.ones((6, 1))
c = np.ones((1, 6))

ab = a + b
ac = a + c
bc = b + c

In [42]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("\nShape of a + b:", ab.shape)
print("Shape of a + c:", ac.shape)
print("Shape of b + c:", bc.shape)


Shape of a: (6,)
Shape of b: (6, 1)
Shape of c: (1, 6)

Shape of a + b: (6, 6)
Shape of a + c: (1, 6)
Shape of b + c: (6, 6)


#### 3.2 Scalar with array

In [44]:
portfolio_values = np.array([10000, 15000, 20000, 25000])
growth_rate = 1.07  # 7% annual growth
future_values = portfolio_values * growth_rate
print(f"Portfolio values: {portfolio_values}")
print(f"After 7% growth: {future_values}")

Portfolio values: [10000 15000 20000 25000]
After 7% growth: [10700. 16050. 21400. 26750.]


#### 3.3 Different shaped arrays

In [ ]:
quarterly_returns = np.array([0.02, 0.03, -0.01, 0.04])  # 4 quarters
yearly_data = np.array([[2020, 2021, 2022],   # Years
                        [0.10, 0.15, -0.05],  # Annual returns
                        [1000, 1100, 1050]])  # Portfolio values
print(f"\nQuarterly returns shape: {quarterly_returns.shape}")
print(f"Yearly data shape: {yearly_data.shape}")

try:
    quarterly_adjustment = quarterly_returns.reshape(4, 1)
    print(f"Quarterly adjustment shape: {quarterly_adjustment.shape}")
except ValueError as e:
    print(f"Broadcasting error: {e}")


Quarterly returns shape: (4,)
Yearly data shape: (3, 3)
Quarterly adjustment shape: (4, 1)


#### 3.4 Practical broadcasting - portfolio rebalancing

In [46]:
weights = np.array([0.4, 0.3, 0.2, 0.1])  # Portfolio weights
asset_returns = np.array([[0.08, 0.12, -0.02, 0.15],   # Asset 1 quarterly returns
                         [0.05, 0.08, 0.03, 0.10],     # Asset 2
                         [0.12, 0.15, -0.05, 0.20],    # Asset 3
                         [0.03, 0.05, 0.02, 0.08]])    # Asset 4

print(f"\nAsset returns shape: {asset_returns.shape}")
print(f"Weights shape: {weights.shape}")

# Calculate portfolio returns using broadcasting
portfolio_returns = np.sum(asset_returns * weights.reshape(-1, 1), axis=0)
print(f"Portfolio quarterly returns: {portfolio_returns}")


Asset returns shape: (4, 4)
Weights shape: (4,)
Portfolio quarterly returns: [ 0.074  0.107 -0.007  0.138]


In [47]:
portfolios = np.array([[0.6, 0.3, 0.1],    # Conservative
                      [0.4, 0.4, 0.2],     # Balanced  
                      [0.2, 0.3, 0.5]])    # Aggressive

asset_performance = np.array([0.05, 0.10, 0.15])  # Expected returns

# Calculate expected returns for each portfolio using broadcasting
expected_returns = np.sum(portfolios * asset_performance, axis=1)
print(f"Portfolio allocations:\n{portfolios}")
print(f"Asset expected returns: {asset_performance}")
print(f"Portfolio expected returns: {expected_returns}")

Portfolio allocations:
[[0.6 0.3 0.1]
 [0.4 0.4 0.2]
 [0.2 0.3 0.5]]
Asset expected returns: [0.05 0.1  0.15]
Portfolio expected returns: [0.075 0.09  0.115]
