In [17]:
import sys
import numpy as np # Numerical Python

### 1. Array Creation & Proporties

#### 1.1 Array Creation Methods

In [6]:
price_list = [21000, 56900, 100, 21, 0]
price_array = np.array(price_list)

print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"shape : {price_array.shape}")

From list : [21000, 56900, 100, 21, 0]
From array : [21000 56900   100    21     0]
shape : (5,)


In [9]:
price_list = [[21000], [56900], [100], [21], [0]]
price_array = np.array(price_list)

print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"shape : {price_array.shape}")

From list : [[21000], [56900], [100], [21], [0]]
From array : [[21000]
 [56900]
 [  100]
 [   21]
 [    0]]
shape : (5, 1)


In [13]:
price_list = [[21000, 56900, 100, 21, 0]]
price_array = np.array(price_list)

print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"shape : {price_array.shape}")

From list : [[21000, 56900, 100, 21, 0]]
From array : [[21000 56900   100    21     0]]
shape : (1, 5)


### 2. Python List vs NumPy Arrays

#### 2.1 Memory

In [16]:
size = 10000
python_list = list(range(size))
numpy_array = np.arange(size)

numpy_array

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [ ]:
list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)
array_memory = numpy_array.nbytes + numpy_array.__sizeof__()

print(f"list memory : {list_memory}")
print(f"array memory : {array_memory}")

list memory : 360056
array memory : 160112


In [20]:
360056 / 160112 

2.2487758569001697

### 3. Vectorization & Broadcasting

#### 3.1 Vectorization

In [29]:
a_list = [1,2,3]
a_array = np.array([1,2,3])

a_list * 3, a_array * 3

([1, 2, 3, 1, 2, 3, 1, 2, 3], array([3, 6, 9]))

[1 1 1 1 1 1]

[
[1]
[1]
[1]
[1]
[1]
[1]
]

[[1 1 1 1 1 1]]

In [ ]:
a = np.ones(6)
b = np.ones((6, 1))
c = np.ones((1, 6))

ac = a + c # 1, 6
ab = a + b # 6, 6 
bc = b + c # 6, 6

There are 3 students 

- Isuru (70, 60, 50, 40)
- Kawshi (40, 50, 20, 10)
- Lochana (90, 90, 80, 70)

4 Subjects 

- Maths 
- Science
- History
- Health

4 Weights 
- 0.5
- 0.4
- 0.07
- 0.03

In [51]:
weights = np.array([0.5, 0.4, 0.07, 0.03]) # (4, )
marks = np.array([
                [70, 60, 50, 40],
                [40, 50, 20, 1],
                [90, 90, 80, 70]
                ]) # (3, 4)

In [ ]:
marks @ weights.reshape(4,1) # be careful when you use * vs @

array([[63.7 ],
       [41.43],
       [88.7 ]])

In [53]:
weights.shape

(4,)

In [56]:
weights.reshape(1, 4)

array([[0.5 , 0.4 , 0.07, 0.03]])